Repository foglamp/FogLAMP, pull requests merged in 2018-12, with the labels that each got.

#1263 Fogl 2145 - plugin discovery API to support C-filter and C-notify plugins
  python/foglamp/common/plugin_discovery.py
  python/foglamp/services/core/api/plugin_discovery.py
  tests/unit/python/foglamp/common/test_plugin_discovery.py
  tests/unit/python/foglamp/services/core/api/test_plugin_discovery_api.py
Labels: architectural_review_done

#1261 FOGL-2014 - recursively delete all child categories and the relationships for delete south service and north task instance
  python/foglamp/common/configuration_manager.py
  python/foglamp/services/core/api/notification.py
  python/foglamp/services/core/api/service.py
  python/foglamp/services/core/api/task.py
  tests/unit/python/foglamp/common/test_configuration_manager.py
  tests/unit/python/foglamp/services/core/api/test_notification.py
  tests/unit/python/foglamp/services/core/api/test_service.py
  tests/unit/python/foglamp/services/core/api/test_task.py
Labels: architectural_review_pending

#1286 FOGL-2081 filter api tests added and service reference removal from its api file
  python/foglamp/services/core/api/filters.py
  tests/unit/python/foglamp/services/core/api/test_filters.py
Labels: unit tests

#1294 FogL 2182 - safe mode startup option
  python/foglamp/services/core/__main__.py
  python/foglamp/services/core/api/common.py
  python/foglamp/services/core/scheduler/scheduler.py
  python/foglamp/services/core/server.py
  scripts/foglamp
  tests/unit/python/foglamp/services/core/api/test_common_ping.py
Labels: architectural_review_done
