Repository foglamp/FogLAMP, pull requests merged in 2018-04, with the labels that each got.

#688 Admin API end point added for user reset role and password
  python/foglamp/common/web/middleware.py
  python/foglamp/services/core/api/auth.py
  python/foglamp/services/core/routes.py
  python/foglamp/services/core/user_model.py
Labels: architectural_review_done

#686 Fogl 1213 - password rotation policy
  python/foglamp/common/web/middleware.py
  python/foglamp/services/core/api/auth.py
  python/foglamp/services/core/routes.py
  python/foglamp/services/core/server.py
  python/foglamp/services/core/user_model.py
  scripts/plugins/storage/postgres/init.sql
  tests/unit/python/foglamp/services/core/api/test_auth_mandatory.py
  tests/unit/python/foglamp/services/core/api/test_auth_optional.py
  tests/unit/python/foglamp/services/core/test_user_model.py
Labels: architectural_review_done

#689 FOGL-862 handling for day fixes when timed schedule
  python/foglamp/services/core/api/scheduler.py
  python/foglamp/services/core/scheduler/exceptions.py
  tests/unit/python/foglamp/services/core/api/test_scheduler_api.py
  tests/unit/python/foglamp/services/core/scheduler/test_scheduler_exceptions.py
Labels: bug

#698 FOGL-1233 add config item REST end-point added
  python/foglamp/services/core/api/configuration.py
  python/foglamp/services/core/routes.py
  tests/unit/python/foglamp/services/core/api/test_configuration.py
Labels: architectural_review_done

#711 FOGL-1122 Tests added for service.py
  python/foglamp/services/core/api/service.py
  tests/unit/python/foglamp/services/core/api/test_service.py
Labels: unit tests

#719 Fogl 1260
  python/foglamp/services/core/server.py
  tests/unit/python/foglamp/services/core/api/test_server.py
  tests/unit/python/foglamp/services/core/test_server.py
Labels: unit tests

#740 FOGL-1284 value error fixes when repeat interval is more than 1 day
  python/foglamp/services/core/api/statistics.py
  python/foglamp/services/core/scheduler/scheduler.py
  tests/unit/python/foglamp/services/core/api/test_statistics_api.py
Labels: bug

#751 FOGL-1292: Data grouped by minutes is fixed
  C/plugins/storage/sqlite/connection.cpp
Labels: in progress
