Repository foglamp/FogLAMP, pull requests merged in 2019-03, with the labels that each got.

#1384 FOGL-2396 System integration test for API
  tests/system/python/api/.gitkeep
  tests/system/python/api/test_configuration.py
  tests/system/python/e2e/test_e2e_coap_OCS.py
  tests/system/python/e2e/test_e2e_expr_pi.py
Labels: in progress

#1474 FOGL-2636: fix a possible memory leak in the usage of the 'escape' function in the postgress and SQLITE
  C/plugins/storage/postgres/connection.cpp
  C/plugins/storage/postgres/include/connection.h
  C/plugins/storage/sqlite/connection.cpp
  C/plugins/storage/sqlite/include/connection.h
  C/plugins/storage/sqlitememory/connection.cpp
  C/plugins/storage/sqlitememory/include/connection.h
Labels: DO NOT MERGE YET

#1481 FOGL-2621 plugin discovery system tests added
  tests/system/python/api/test_plugin_discovery.py
  tests/system/python/scripts/install_c_plugin
  tests/system/python/scripts/reset_plugins
Labels: System Test
